[libraries]
annotations = "org.jetbrains:annotations:23.0.0"
junit = "org.junit.jupiter:junit-jupiter:5.9.1"
algoutils-student = "org.tudalgo:algoutils-student:0.3.0"

[plugins]
jagr = "org.sourcegrade.jagr-gradle:0.6.0"
